basic.showString("Hello!")
basic.showString("I am")
basic.showString("VicRodger27")
music.playTone(988, music.beat(BeatFraction.Quarter))
basic.showString("I love microbits,football and to play on my ")
basic.showString("tablet+nentendo swich. <3")
basic.showIcon(IconNames.Heart)
basic.showString("Bye!")
basic.pause(5000)
basic.clearScreen()
